### Get all  articles 
### // GET articles/
GET http://localhost:3000/articles/

### Get articles by ID
### // GET articles/id
GET http://localhost:3000/articles/67f34a48bd17c2cc36187b24

### Create a new article
### // POST articles/
POST http://localhost:3000/articles/
Content-Type: application/json

{
 "title": "Article Title",
 "content": "Article Content"
}

### Update an article
### // PUT articles/id
PUT http://localhost:3000/articles/67f34a48bd17c2cc36187b24
Content-Type: application/json

{
 "title": "Article Title Test",
 "content": "Article Content Test"
}

### Delete an existing article
### // DELETE articles/id
DELETE http://localhost:3000/articles/67f34a48bd17c2cc36187b24